### ISSUE TITLE
Migration to React

### ISSUE THREAD

**Issue by nnivxix** [nnivxix/vilm#1]

**Comment by DonMiller9294** [comment]
Hey could you give a description of the issue you are facing?

**Comment by nnivxix** [comment]
I just want to migration from Vue to React

**Comment by VishalChangder00789** [comment]
hey can i help you?

**Comment by DonMiller9294** [comment]
i found this on a forum, have you tried this? 
https://betterprogramming.pub/how-to-incrementally-migrate-from-vue-js-2-to-react-18-part-1-setup-be2cd04458f0

**Comment by nnivxix** [comment]
@VishalChangder00789 yes you can, but the issue not yet started, I haven't made a design and what todo needs to be done.

@DonMiller9294 interesting, thanks

**Comment by VishalChangder00789** [comment]
@nnivxix  Hey , once you have the design , i can help you build the Front end part.

**Comment by nnivxix** [comment]
Hi all, this repository has migrated to React.

sometimes I open issues, so stay tune.
